// ErrorDefinitions.h
#ifndef ERROR_DEFINITIONS_H
#define ERROR_DEFINITIONS_H

#define ERR_SD_NOT_DETECTED "ERR: SD 01"
#define ERR_JSON_READ "ERR: JSON 01"
#define ERR_WIFI_CONNECT_FAIL "ERR: WIFI 01"
#define ERR_ETHERNET_CONNECT_FAIL "ERR: ETH 01"

#endif // ERROR_DEFINITIONS_H
